/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IZNEWUniswapV2PairEncrypted,
  IZNEWUniswapV2PairEncryptedInterface,
} from "../../interfaces/IZNEWUniswapV2PairEncrypted";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "address",
        name: "_token0",
        type: "address",
      },
      {
        internalType: "address",
        name: "_token1",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "initialLiquidity",
        type: "uint32",
      },
      {
        internalType: "uint8",
        name: "initialActiveBin",
        type: "uint8",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint32[]",
        name: "liquidities",
        type: "uint32[]",
      },
      {
        internalType: "uint8[]",
        name: "indexLiquidities",
        type: "uint8[]",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "amount0",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "amount1",
        type: "uint32",
      },
    ],
    name: "swap",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IZNEWUniswapV2PairEncrypted__factory {
  static readonly abi = _abi;
  static createInterface(): IZNEWUniswapV2PairEncryptedInterface {
    return new Interface(_abi) as IZNEWUniswapV2PairEncryptedInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IZNEWUniswapV2PairEncrypted {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IZNEWUniswapV2PairEncrypted;
  }
}
