/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ILBToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILBToken__factory>;
    getContractFactory(
      name: "IZNEWEncryptedERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IZNEWEncryptedERC20__factory>;
    getContractFactory(
      name: "IZNEWUniswapV2PairEncrypted",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IZNEWUniswapV2PairEncrypted__factory>;
    getContractFactory(
      name: "LBToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LBToken__factory>;
    getContractFactory(
      name: "ZNEWEncryptedERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZNEWEncryptedERC20__factory>;
    getContractFactory(
      name: "ZNEWUniswapV2FactoryEncrypted",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZNEWUniswapV2FactoryEncrypted__factory>;
    getContractFactory(
      name: "ZNEWUniswapV2PairEncrypted",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZNEWUniswapV2PairEncrypted__factory>;

    getContractAt(
      name: "ILBToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILBToken>;
    getContractAt(
      name: "IZNEWEncryptedERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IZNEWEncryptedERC20>;
    getContractAt(
      name: "IZNEWUniswapV2PairEncrypted",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IZNEWUniswapV2PairEncrypted>;
    getContractAt(
      name: "LBToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LBToken>;
    getContractAt(
      name: "ZNEWEncryptedERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ZNEWEncryptedERC20>;
    getContractAt(
      name: "ZNEWUniswapV2FactoryEncrypted",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ZNEWUniswapV2FactoryEncrypted>;
    getContractAt(
      name: "ZNEWUniswapV2PairEncrypted",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ZNEWUniswapV2PairEncrypted>;

    deployContract(
      name: "ILBToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILBToken>;
    deployContract(
      name: "IZNEWEncryptedERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IZNEWEncryptedERC20>;
    deployContract(
      name: "IZNEWUniswapV2PairEncrypted",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IZNEWUniswapV2PairEncrypted>;
    deployContract(
      name: "LBToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LBToken>;
    deployContract(
      name: "ZNEWEncryptedERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZNEWEncryptedERC20>;
    deployContract(
      name: "ZNEWUniswapV2FactoryEncrypted",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZNEWUniswapV2FactoryEncrypted>;
    deployContract(
      name: "ZNEWUniswapV2PairEncrypted",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZNEWUniswapV2PairEncrypted>;

    deployContract(
      name: "ILBToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILBToken>;
    deployContract(
      name: "IZNEWEncryptedERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IZNEWEncryptedERC20>;
    deployContract(
      name: "IZNEWUniswapV2PairEncrypted",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IZNEWUniswapV2PairEncrypted>;
    deployContract(
      name: "LBToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LBToken>;
    deployContract(
      name: "ZNEWEncryptedERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZNEWEncryptedERC20>;
    deployContract(
      name: "ZNEWUniswapV2FactoryEncrypted",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZNEWUniswapV2FactoryEncrypted>;
    deployContract(
      name: "ZNEWUniswapV2PairEncrypted",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZNEWUniswapV2PairEncrypted>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
